name: PR -> Master Workflow

on:
    pull_request:
        branches:
            - master

jobs:
    lint-test-build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '16'
            - name: Install Dependencies
              run: npm install
            - name: Lint
              run: npm run lint
            - name: Lint YML
              run: npm run lint:yaml
            # - name: Test
            #   run: npm test
            - name: Build
              run: npm run build
