name: PR Merged into publish/live

on:
    push:
        branches:
            - 'publish/live'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '16'
            - name: Install Dependencies
              run: npm install
            - name: Build
              run: npm run build
            - name: Publish
              run: npm run publish --access=public
